# Generated by Django 5.2.9 on 2025-12-28 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_alter_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clube',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('pais', models.CharField(max_length=50)),
                ('ano_fundacao', models.IntegerField()),
                ('escudo', models.ImageField(blank=True, null=True, upload_to='escudos/')),
            ],
        ),
    ]
