# Generated by Django 4.2.27 on 2026-01-06 03:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_clube'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jogador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('idade', models.IntegerField()),
                ('peso', models.FloatField(help_text='Peso em kg')),
                ('altura', models.FloatField(help_text='Altura em metros')),
                ('nacionalidade', models.CharField(max_length=50)),
                ('posicao', models.CharField(choices=[('Goleiro', 'Goleiro'), ('Zagueiro', 'Zagueiro'), ('Lateral Esquerdo', 'Lateral Esquerdo'), ('Lateral Direito', 'Lateral Direito'), ('Volante', 'Volante'), ('Meio-campista', 'Meio-campista'), ('Meia Atacante', 'Meia Atacante'), ('Ponta Esquerda', 'Ponta Esquerda'), ('Ponta Direita', 'Ponta Direita'), ('Centroavante', 'Centroavante')], max_length=30)),
                ('perna', models.CharField(choices=[('Destro', 'Destro'), ('Canhoto', 'Canhoto'), ('Ambidestro', 'Ambidestro')], max_length=20)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='jogadores/')),
                ('clube', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jogadores', to='backend.clube')),
            ],
        ),
    ]
