# Generated by Django 5.2.9 on 2026-01-07 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_jogador'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competicao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('tamanho', models.CharField(max_length=50)),
                ('localidade', models.CharField(blank=True, max_length=100, null=True)),
                ('tipo_participantes', models.CharField(max_length=50)),
                ('divisao', models.CharField(max_length=50)),
                ('tipo_formato', models.CharField(max_length=50)),
                ('qtd_participantes', models.IntegerField(default=0)),
                ('tem_trofeu', models.BooleanField(default=False)),
                ('tem_premiacao_financeira', models.BooleanField(default=False)),
                ('valor_premiacao', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('garante_vaga', models.BooleanField(default=False)),
                ('competicao_destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.competicao')),
            ],
        ),
    ]
