# Generated by Django 6.0.1 on 2026-01-13 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_competicao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clube',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='competicao',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='jogador',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='Partida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora', models.DateTimeField()),
                ('local', models.CharField(blank=True, max_length=150, null=True)),
                ('placar_mandante', models.IntegerField(default=0)),
                ('placar_visitante', models.IntegerField(default=0)),
                ('competicao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.competicao')),
                ('mandante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidas_mandante', to='backend.clube')),
                ('visitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidas_visitante', to='backend.clube')),
            ],
        ),
        migrations.CreateModel(
            name='Gol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minuto', models.IntegerField(blank=True, help_text='Minuto do gol', null=True)),
                ('assistencia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assistencias_feitas', to='backend.jogador')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gols_marcados', to='backend.jogador')),
                ('partida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gols', to='backend.partida')),
            ],
        ),
    ]
